#!/usr/bin/env bash
# detect-tools.sh — Unix counterpart of detect-tools.ps1.
#
# Detects which supported tools are installed (by checking each tool's marker
# directory from supported-tools.json) and writes a config.json that only
# includes the ones present. Paths in the generated config stay in portable
# %VAR% form so the same file works on any machine.
#
# Usage:
#   ./detect-tools.sh           # only tools whose marker dir exists
#   ./detect-tools.sh --all     # include every supported tool
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CATALOG="$SCRIPT_DIR/supported-tools.json"
CONFIG="$SCRIPT_DIR/config.json"
ALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        --all|-All|-all) ALL=1; shift ;;
        -h|--help)
            echo "Usage: $0 [--all]"
            exit 0
            ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

if ! command -v python3 >/dev/null 2>&1; then
    echo "[ERROR] python3 is required to generate config.json (not found on PATH)." >&2
    exit 1
fi

if [ ! -f "$CATALOG" ]; then
    echo "[ERROR] catalog not found: $CATALOG" >&2
    exit 1
fi

python3 - "$CATALOG" "$CONFIG" "$ALL" <<'PY'
import json
import os
import sys

catalog_path, config_path, all_flag = sys.argv[1], sys.argv[2], sys.argv[3] == "1"

with open(catalog_path, encoding="utf-8") as handle:
    catalog = json.load(handle)
tools = catalog.get("tools") or []
if not tools:
    print("[ERROR] supported-tools.json has no tools", file=sys.stderr)
    sys.exit(1)


def expand_marker(value):
    """Expand a catalog path just enough to Test-Path equivalent on this Unix host."""
    value = value.replace("\\", "/")
    value = value.replace("%USERPROFILE%", os.path.expanduser("~"))
    value = value.replace(
        "%APPDATA%",
        os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")),
    )
    value = value.replace("%LOCALAPPDATA%", os.path.expanduser("~/.local/share"))
    if "HERMES_HOME" in os.environ:
        value = value.replace("%HERMES_HOME%", os.environ["HERMES_HOME"])
    value = os.path.expandvars(value)
    return value


existing = {}
if os.path.isfile(config_path):
    try:
        with open(config_path, encoding="utf-8") as handle:
            existing = json.load(handle)
    except (OSError, json.JSONDecodeError):
        existing = {}

targets = {}
found = []
missed = []
for tool in tools:
    name = tool["name"]
    marker = expand_marker(tool["marker"])
    unresolved = "%" in marker
    present = (not unresolved) and os.path.exists(marker)
    if all_flag or present:
        if tool.get("mode"):
            targets[name] = {"path": tool["skills"], "mode": tool["mode"]}
        else:
            targets[name] = tool["skills"]
        found.append(name)
    else:
        missed.append(name)

catalog_names = {tool["name"] for tool in tools}
kept_extra = []
for name, value in (existing.get("targets") or {}).items():
    if name not in catalog_names:
        targets[name] = value
        kept_extra.append(name)

autolink = existing.get("autolink") or {}
cfg = {
    "$comment": "SkillBridge - auto-generated by detect-tools.sh for THIS machine.",
    "link_type": existing.get("link_type") or "symlink",
    "source": existing.get("source") or "%USERPROFILE%\\.cc-switch\\skills",
    "targets": targets,
    "autolink": {
        "enabled": autolink["enabled"] if "enabled" in autolink else True,
        "at_logon": autolink["at_logon"] if "at_logon" in autolink else True,
        "interval_minutes": autolink["interval_minutes"] if "interval_minutes" in autolink else 0,
    },
    "check_db": existing["check_db"] if "check_db" in existing else True,
}

with open(config_path, "w", encoding="utf-8", newline="\n") as handle:
    json.dump(cfg, handle, indent=2, ensure_ascii=False)
    handle.write("\n")

print("Detected %d / %d supported tools." % (len(found), len(tools)))
print("  installed : %s" % (", ".join(found) if found else "(none)"))
if missed:
    print("  not found : %s" % ", ".join(missed))
if kept_extra:
    print("  kept extra : %s" % ", ".join(kept_extra))
print("config.json written. Now run ./sync-skills.sh")
PY
