#!/usr/bin/env bash
# detect-tools.sh — Unix counterpart of detect-tools.ps1.
#
# Detects which supported tools are installed (by checking each tool's marker
# directory from supported-tools.json) and writes a config.json that only
# includes the ones present. Paths in the generated config stay in portable
# %VAR% form so the same file works on any machine.
#
# Usage:
#   ./detect-tools.sh                          # only tools whose marker dir exists
#   ./detect-tools.sh --all                    # include every supported tool
#   ./detect-tools.sh --config /path/config.json   # write somewhere else
#
# Tools listed in the config's `exclude` array are never written to `targets`,
# even with --all — that is how a deliberately removed target stays removed.
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CATALOG="$SCRIPT_DIR/supported-tools.json"
CONFIG="$SCRIPT_DIR/config.json"
ALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        --all|-All|-all) ALL=1; shift ;;
        --config)
            # Guard the value: `shift 2` with only one argument left fails silently
            # and leaves $1 unchanged, so the loop would spin forever with no output.
            if [ $# -lt 2 ] || [ -z "$2" ]; then
                echo "[ERROR] --config needs a path" >&2
                exit 1
            fi
            CONFIG="$2"; shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [--all] [--config PATH]"
            exit 0
            ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

if ! command -v python3 >/dev/null 2>&1; then
    echo "[ERROR] python3 is required to generate config.json (not found on PATH)." >&2
    exit 1
fi

if [ ! -f "$CATALOG" ]; then
    echo "[ERROR] catalog not found: $CATALOG" >&2
    exit 1
fi

python3 - "$CATALOG" "$CONFIG" "$ALL" <<'PY'
import json
import os
import sys

catalog_path, config_path, all_flag = sys.argv[1], sys.argv[2], sys.argv[3] == "1"

with open(catalog_path, encoding="utf-8") as handle:
    catalog = json.load(handle)
tools = catalog.get("tools") or []
if not tools:
    print("[ERROR] supported-tools.json has no tools", file=sys.stderr)
    sys.exit(1)


def expand_marker(value):
    """Expand a catalog path just enough to Test-Path equivalent on this Unix host."""
    value = value.replace("\\", "/")
    value = value.replace("%USERPROFILE%", os.path.expanduser("~"))
    value = value.replace(
        "%APPDATA%",
        os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")),
    )
    value = value.replace("%LOCALAPPDATA%", os.path.expanduser("~/.local/share"))
    if "HERMES_HOME" in os.environ:
        value = value.replace("%HERMES_HOME%", os.environ["HERMES_HOME"])
    value = os.path.expandvars(value)
    return value


existing = {}
if os.path.isfile(config_path):
    try:
        with open(config_path, encoding="utf-8") as handle:
            existing = json.load(handle)
    except (OSError, json.JSONDecodeError):
        existing = {}

catalog_names = {tool["name"] for tool in tools}

# `exclude` is the user's explicit opt-out. A tool listed here is never written to
# `targets`, even when its marker directory exists and even with --all. Without it,
# re-running detect-tools silently resurrected a target that was removed on purpose
# (the marker dir of an uninstalled-but-lingering tool stays on disk forever).
exclude_raw = existing.get("exclude") or []
if isinstance(exclude_raw, str):
    exclude_raw = [exclude_raw]
exclude_set = {str(n) for n in exclude_raw if n}
# Rewrite in catalog order so the file stays stable between runs, and a typo in
# `exclude` does not survive forever.
excluded = [tool["name"] for tool in tools if tool["name"] in exclude_set]
excluded_unknown = [n for n in exclude_raw if str(n) not in catalog_names]

targets = {}
found = []
missed = []
for tool in tools:
    name = tool["name"]
    if name in exclude_set:
        continue
    marker = expand_marker(tool["marker"])
    unresolved = "%" in marker
    present = (not unresolved) and os.path.exists(marker)
    if all_flag or present:
        if tool.get("mode"):
            targets[name] = {"path": tool["skills"], "mode": tool["mode"]}
        else:
            targets[name] = tool["skills"]
        found.append(name)
    else:
        missed.append(name)

kept_extra = []
for name, value in (existing.get("targets") or {}).items():
    if name not in catalog_names:
        targets[name] = value
        kept_extra.append(name)

autolink = existing.get("autolink") or {}
cfg = {
    # Keep a hand-edited $comment: it is where machine-specific migration notes live.
    "$comment": existing.get("$comment")
    or "SkillBridge - auto-generated by detect-tools.sh for THIS machine.",
    "link_type": existing.get("link_type") or "symlink",
    "source": existing.get("source") or "%USERPROFILE%\\.cc-switch\\skills",
    "exclude": excluded,
    "targets": targets,
    "autolink": {
        "enabled": autolink["enabled"] if "enabled" in autolink else True,
        "at_logon": autolink["at_logon"] if "at_logon" in autolink else True,
        "interval_minutes": autolink["interval_minutes"] if "interval_minutes" in autolink else 0,
    },
    # Default OFF: the check only reports, but it is an extra python invocation and
    # its finding is only meaningful to someone who will act on it.
    "check_db": existing["check_db"] if "check_db" in existing else False,
}

with open(config_path, "w", encoding="utf-8", newline="\n") as handle:
    json.dump(cfg, handle, indent=2, ensure_ascii=False)
    handle.write("\n")

print("Detected %d / %d supported tools." % (len(found), len(tools)))
print("  installed : %s" % (", ".join(found) if found else "(none)"))
if missed:
    print("  not found : %s" % ", ".join(missed))
if excluded:
    print("  excluded  : %s  (kept out by config `exclude`)" % ", ".join(excluded))
if excluded_unknown:
    print(
        "  WARNING   : config `exclude` names not in supported-tools.json (dropped): %s"
        % ", ".join(str(n) for n in excluded_unknown),
        file=sys.stderr,
    )
if kept_extra:
    print("  kept extra : %s" % ", ".join(kept_extra))

# The scheduled sync runs from cron/launchd, where failures go nowhere. Read the
# record it leaves behind; a `fail` here usually means the autolink entry is broken.
status_path = os.path.join(
    os.path.dirname(os.path.abspath(config_path)), ".skillbridge-status.json"
)
try:
    with open(status_path, encoding="utf-8") as handle:
        last = json.load(handle)
    note = " - %s" % last["message"] if last.get("message") else ""
    state = last.get("status")
    when = last.get("at")
    if state == "fail":
        print("  WARNING   : last sync run FAILED at %s%s" % (when, note), file=sys.stderr)
    elif state == "warn":
        print("  WARNING   : last sync run finished with a warning at %s%s" % (when, note), file=sys.stderr)
    elif when:
        print("  last sync : ok at %s" % when)
except (OSError, json.JSONDecodeError, KeyError):
    pass

print("config.json written. Now run ./sync-skills.sh")
PY
